name: yotsuba_gantt_example
description: Yotsuba Gantt Flutter example.
publish_to: none
version: 0.1.0-alpha.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  yotsuba_gantt:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
